Removes use of removed `-f` option in `docker tag` command
OS: `OSX 10.11.6`

```bash
$ docker --version
Docker version 1.12.0, build 8eab29e
```

The `./build_all.sh` script errors:

```
...
Removing intermediate container 2cff0a33c256
Step 5 : VOLUME /var/log/raintank
 ---> Running in eab0eec9a218
 ---> 525c73885022
Removing intermediate container eab0eec9a218
Successfully built 525c73885022
unknown shorthand flag: 'f' in -f
See 'docker tag --help'.
ERROR: failed building nodejs. stopping.
```

It appears that `docker tag` no longer accepts the `-f` flag to force
the operation. References: [Docker
forum](https://forums.docker.com/t/force-tag-f-option-removed/18782),
[stackoverflow](http://stackoverflow.com/questions/38127037/how-to-force-a-docker-push-on-mac-osx).

This change removes the use of the `-f` flag from the `docker tag`
command. It does not address [backwards
compatibility](https://forums.docker.com/t/docker-1-12-breaks-docker-tag-f-in-scripts/16992)
with older docker versions.